### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by JenilGajjar20** [JenilGajjar20/React-imageGallery#1]

**Comment by Snehil0603** [comment]
I would like to work on documentation . Kindly assign me this issue.

**Comment by Gopal2021025** [comment]
I would like to work on it

**Comment by Snehil0603** [comment]
@JenilGajjar20 
My account is facing some issues can you please assign it to @Gopal2021025

**Comment by JenilGajjar20** [comment]
What kind of issues you are facing? @Snehil0603

**Comment by JenilGajjar20** [comment]
Go for it @Gopal2021025
